# Generated by Django 3.2.19 on 2023-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredientImage',
        ),
    ]
