# Generated by Django 3.2.19 on 2023-05-13 18:09

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='upload',
            field=models.FileField(upload_to=recipes.models.ingredient_directory_path),
        ),
    ]
