# Generated by Django 3.2.19 on 2023-05-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredientimage_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredientimage',
            old_name='upload',
            new_name='image',
        ),
    ]
